pipeline {
  agent any
  tools {
    maven 'M3' 
  }
  stages {
    stage ('Build') {
      steps {
      	bat 'cd hello'       
      }
      steps {      	
        bat 'mvn clean package'
      }
    }
  }
}